apiVersion: v1
kind: Service
metadata:
  name: elk-zk-headless
  namespace: logging
  labels:
    app: elk-zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: elk-zk
