apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: monitoring
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-exporter
      team: devops
  template:
    metadata:
      labels:
        app: kafka-exporter
      annotations:
        prometheus.io/port: "9308"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:v1.2.0
        imagePullPolicy: Always
        args:
        - --kafka.server=elk-kafka-0.elk-kafka-headless.logging.svc.cluster.local:9092
        - --kafka.server=elk-kafka-1.elk-kafka-headless.logging.svc.cluster.local:9092
        - --kafka.server=elk-kafka-2.elk-kafka-headless.logging.svc.cluster.local:9092
        ports:
        - containerPort: 9308
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 10Mi
